apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: nginx
      image: nginx
    - name: nginx-helper
      image: vinsdocker/util
      args:
        - "sleep"
        - "3600"