apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: c2Fzc2FtYW4K
  password: cGFzc3dvcmQK
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      envFrom:
        - secretRef:
            name: app-secret
      args:
        - env