apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties
data:
  appUrl: "http://my-app-service"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      env:
        - name: "request.timeout"
          valueFrom:
            configMapKeyRef:
              key: timeout
              name: application-properties
        - name: "application.url"
          valueFrom:
            configMapKeyRef:
              key: appUrl
              name: application-properties
      args:
        - env