apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: c2Fzc2FtYW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      env:
        - name: "app_username"
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: "app_password"
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
      args:
        - env