services:
  mongodb:
    image: mongo
    ports:
      - "${HOST_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: job_user
      MONGO_INITDB_ROOT_PASSWORD: job_password
    volumes:
      - ./src/test/resources/data:/docker-entrypoint-initdb.d
    networks:
      - job-service-network

  job-service:
    image: ssamantr/job-service:1.0.0
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    profiles:
      - app
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongodb:27017/job"
    networks:
      - job-service-network

networks:
  job-service-network:
