version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "${HOST_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: candidate_user
      MONGO_INITDB_ROOT_PASSWORD: candidate_password
    volumes:
      - ./src/test/resources/data:/docker-entrypoint-initdb.d
    networks:
      - candidate-service-network

  job-service:
    image: ssamantr/candidate-service:1.0.0
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    profiles:
      - app
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongodb:27017/candidate"
    networks:
      - candidate-service-network

networks:
  candidate-service-network:
