apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
spec:
  selector:
    matchLabels:
      app-label: my-app
  replicas: 3
  template:
    metadata:
      name: my-pod
      labels:
        app-label: my-app
    spec:
      containers:
        - name: nginx
          image: nginx