# To make use of mongo secrets we are using k8s Secrets
apiVersion: v1
kind: Secret
metadata:
  name: employee-db-secrets
data:
  spring.data.mongodb.uri: bW9uZ29kYjovL2VtcGxveWVlX3VzZXI6ZW1wbG95ZWVfcGFzc3dvcmRAbW9uZ29kYjoyNzAxNy9lbXBsb3llZQ==
