# Actual Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-assignment
spec:
  selector:
    matchLabels:
      app-label: application-assignment
  replicas: 1
  template:
    metadata:
      labels:
        app-label: application-assignment
    spec:
      containers:
        - name: application-assignment
          image: vinsdocker/k8s-deploy-assignment
          ports:
            - name: "app-port"
              containerPort: 8080
          env:
            - name: "spring.redis.host"
              value: "redis"
            - name: "spring.redis.port"
              value: "6379"

# Actual Redis Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-container
spec:
  selector:
    matchLabels:
      app-label: redis
  replicas: 1
  template:
    metadata:
      labels:
        app-label: redis
    spec:
      containers:
        - name: redis-container
          image: redis:6
          ports:
            - name: "redis-port"
              containerPort: 6379

# Kubernetes Service which encapsulates redis container
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app-label: redis
  ports:
    - port: 6379
      targetPort: 6379