apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  annotations:
        kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app-name: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app-name: order-service
    spec:
      containers:
        - name: order-service
          image: vinsdocker/k8s-app:v2
          ports:
            - name: "app-port"
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app-name: order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: demo
      image: vinsdocker/util
      args:
        - "sleep"
        - "3600"