apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app-label: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app-label: my-app
    spec:
      containers:
        - name: nginx
          image: nginx
          startupProbe: # for demo
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'echo "$(hostname)</br>" >> /usr/share/nginx/html/index.html'
          volumeMounts:
            - name: deployment-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: deployment-volume
          persistentVolumeClaim:
            claimName: my-pvc