apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-stateful-set
spec:
  selector:
    matchLabels:
      app-label: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app-label: my-app
    spec:
      containers:
        - name: nginx
          image: nginx
          startupProbe: # for demo
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'echo "$(hostname)</br>" >> /usr/share/nginx/html/index.html'
          volumeMounts:
            - name: my-dynamic-pvc
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # volumeClaimTemplates is part of statefulSet only
    - metadata:
        name: my-dynamic-pvc
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G