apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-volume
      persistentVolumeClaim:
        claimName: my-pvc
