apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard # Default Storage Class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
