apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  annotations:
#    kubernetes.io/change-cause: "deploying v1"
#    kubernetes.io/change-cause: "deploying v2"
    kubernetes.io/change-cause: "deploying v3"
spec:
  selector:
    matchLabels:
      app-name: order-service
  replicas: 2
  template:
    metadata:
      labels:
        app-name: order-service
    spec:
      containers:
        - name: order-service
#          image: vinsdocker/k8s-app:v1
#          image: vinsdocker/k8s-app:v2
          image: vinsdocker/k8s-app:v3
          ports:
            - name: "app-port"
              containerPort: 80