services:
  web-app:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - docker-compose-network
  util:
    image: vinsdocker/util
    depends_on:
      - web-app
    command: "curl http://web-app"
    networks:
      - docker-compose-network

networks:
  docker-compose-network:
