version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: "address"
      MYSQL_USER: "address_user"
      MYSQL_PASSWORD: "address_password"
      MYSQL_ROOT_PASSWORD: "Sashank@1991"
    ports:
      - "3306:3306"
    volumes:
      - "./address-service/src/test/resources/data:/docker-entrypoint-initdb.d/"
    networks:
      - deployment-network

  mongodb:
    image: mongo
    ports:
      - "${MONGO_DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: employee_user
      MONGO_INITDB_ROOT_PASSWORD: employee_password
    volumes:
      - "./employee-service/src/test/resources/data:/docker-entrypoint-initdb.d"
    networks:
      - deployment-network

  employee-service:
    image: ssamantr/employee-service:1.0.0
    depends_on:
      - mongodb
      - mysql
      - address-service
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://employee_user:employee_password@mongodb:27017/employee"
      address.service.url: "http://address-service:8081/address"
    networks:
      - deployment-network

  address-service:
    image: ssamantr/address-service:1.0.0
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/address"
    networks:
      - deployment-network

networks:
  deployment-network: