# To make use of mongo secrets we are using k8s Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: cm9vdA==
  ME_CONFIG_MONGODB_ADMINPASSWORD: cm9vdHBhc3N3b3Jk