# To initialize data into mongo container, we are creating a k8s configMap and inject data.js as file
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-js
data:
  data.js: |
    db = db.getSiblingDB('product-service');
    db.createCollection('products');
    db.products.insertMany(
        [
            {
                "name":"iphone",
                "price": "1200"
            },
            {
                "name":"ipad",
                "price": "800"
            },
            {
                "name":"mac",
                "price": "3000"
            }
        ]
    )