apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dice
spec:
  rules:
    - http:
        paths:
          - path: /api/candidates
            pathType: Prefix
            backend:
              service:
                name: candidate-service
                port:
                  number: 8080
          - path: /api/jobs
            pathType: Prefix
            backend:
              service:
                name: job-service
                port:
                  number: 8080