apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app-label: my-app
  replicas: 5
  template:
    metadata:
      labels:
        app-label: my-app
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: "1"
              memory: 50Mi
            limits:
              cpu: "2"
              memory: 100Mi