apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10