server:
  port: 8081

spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/address
    username: address_user
    password: address_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true