services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  # Go through "Initializing a fresh instance" in mongo official page.

  # If mongo express does not work, then use Robo 3T instead which is already downloaded.
  mongo-db-admin:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
      ME_CONFIG_MONGODB_SERVER: mongodb