version: "3.8"

services:
  mongodb:
    image: mongo
    volumes:
      - "./data:/docker-entrypoint-initdb.d"

  candidate-service:
    image: ssamantr/candidate-service:1.0.0
    deploy:
      replicas: 2
    depends_on:
      - mongodb
      - job-service
    environment:
      spring.data.mongodb.uri: "mongodb://root:rootpassword@mongodb:27017/candidate"
      job.service.url: "http://job-service:8080/jobs/"

  job-service:
    image: ssamantr/job-service:1.0.0
    deploy:
      replicas: 2
    depends_on:
      - mongodb
    environment:
      spring.data.mongodb.uri: "mongodb://root:rootpassword@mongodb:27017/job"

  nginx:
    image: nginx
    depends_on:
      - candidate-service
      - job-service
    ports:
      - "9090:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./html/index.html:/usr/share/nginx/html/index.html"