# prefer httpGet or tcpSocket probe types
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      startupProbe:
        exec:
          command:
          - "cat"
          - "/usr/share/nginx/html/index.html"
        periodSeconds: 1
        failureThreshold: 3